"""Local development storage; routes depend on this interface, not disk paths."""
import os
from pathlib import Path
import re
from uuid import uuid4


class StorageWriteError(OSError):
    """A partial file needs durable cleanup after a failed write."""
    def __init__(self, storage_key):
        super().__init__("A partial upload could not be removed.")
        self.storage_key = storage_key


class LocalAttachmentStorage:
    def __init__(self, root):
        self.root = Path(root).resolve()

    def build_storage_path(self, storage_key):
        # Accept only keys generated by this backend, on both Windows and POSIX.
        if not isinstance(storage_key, str) or not re.fullmatch(
            r"papers/[1-9][0-9]*/[0-9a-f]{32}\.(pdf|jpg|jpeg|png|webp|pptx|docx)",
            storage_key,
        ):
            raise ValueError("Invalid storage key.")
        path = self.root.joinpath(*storage_key.split("/"))
        if not path.resolve().is_relative_to(self.root):
            raise ValueError("Invalid storage key.")
        return path

    def save_file(self, stream, paper_id, extension):
        key = f"papers/{paper_id}/{uuid4().hex}.{extension}"
        path = self.build_storage_path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Recheck containment after creating directories (including junctions).
        path = self.build_storage_path(key)
        destination = path.open("xb")
        try:
            with destination:
                stream.seek(0)
                while chunk := stream.read(1024 * 1024):
                    destination.write(chunk)
                destination.flush()
                os.fsync(destination.fileno())
        except Exception:
            try:
                path.unlink(missing_ok=True)
            except OSError:
                raise StorageWriteError(key) from None
            raise
        return key

    def replace_file(self, stream, paper_id, extension):
        # Never overwrite/delete the previous file before the DB commits.
        return self.save_file(stream, paper_id, extension)

    def open_file(self, storage_key):
        return self.build_storage_path(storage_key).open("rb")

    def delete_file(self, storage_key):
        try:
            self.build_storage_path(storage_key).unlink()
        except FileNotFoundError:
            return False
        return True
