import { useCallback, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { coursePath, modulePath } from '../api/courses'
import { courseRequest, courseWrite, getReadings, CourseManagementError, type ManagedCourse, type ManagedModule, type CourseStaffMember } from '../api/courseManagement'
import { fetchPapers } from '../api/papers'
import { useCourseRead } from '../hooks/useCourseRead'
import { useAuth } from '../auth/useAuth'
import type { AuthUser } from '../types/auth'
import CourseResourcesEditor, { type CourseRun } from '../components/courses/CourseResourcesEditor'
import './CourseManagementPage.css'

function ContentEditor({ row, base, module, run, busy }: { row: ManagedCourse | ManagedModule; base: string; module?: boolean; run: CourseRun; busy: boolean }) {
  const [description,setDescription]=useState(row.description),[status,setStatus]=useState(row.status),[focus,setFocus]=useState('learningFocus' in row?row.learningFocus:''),[category,setCategory]=useState('category' in row?row.category:'')
  const submit=(e:FormEvent)=>{e.preventDefault();void run(()=>courseWrite(base,'PATCH',{description,status,expectedUpdatedAt:row.updatedAt,...(module?{learningFocus:focus,category}:{})}))}
  return <section className="course-editor-panel"><h2>{module?'Module content':'Course content'}</h2><form onSubmit={submit}>
    <label htmlFor={`${base}-description`}>Description</label><textarea id={`${base}-description`} rows={5} required maxLength={6000} value={description} onChange={e=>setDescription(e.target.value)} />
    {module&&<><label htmlFor={`${base}-focus`}>Learning focus</label><textarea id={`${base}-focus`} rows={4} required maxLength={6000} value={focus} onChange={e=>setFocus(e.target.value)} /><label>Category<input required maxLength={150} value={category} onChange={e=>setCategory(e.target.value)} /></label></>}
    <label htmlFor={`${base}-status`}>Publication status</label><select id={`${base}-status`} value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select>
    <button type="submit" disabled={busy}>{module?'Save module':'Save course'}</button>
  </form></section>
}
function ReadingsEditor({ base,run,busy }: {base:string;run:CourseRun;busy:boolean}) {
  const reader=useCallback((signal:AbortSignal)=>getReadings(base+'/papers',signal),[base]),readings=useCourseRead(base,reader)
  const [input,setInput]=useState(''),[q,setQ]=useState(''),[page,setPage]=useState(1),[readingType,setReadingType]=useState('recommended')
  const searchReader=useCallback((signal:AbortSignal)=>fetchPapers({q,page,perPage:10,signal}),[q,page]),papers=useCourseRead(`papers:${q}:${page}`,searchReader)
  const change:CourseRun=async action=>{const saved=await run(action);if(saved)readings.retry();return saved}
  const move=(index:number,direction:number)=>{const ids=readings.data!.map(r=>r.relationId);[ids[index],ids[index+direction]]=[ids[index+direction],ids[index]];void change(()=>courseWrite(base+'/papers/order','PUT',{relationIds:ids}))}
  return <section className="course-editor-panel"><h2>Module readings</h2>
    {readings.loading?<p role="status">Loading readings…</p>:readings.error?<><p role="alert">Readings unavailable.</p><button type="button" onClick={readings.retry}>Retry readings</button></>:!readings.data?.length?<p>No papers associated.</p>:<ol>{readings.data.map((r,i)=><li key={r.relationId}>{r.paper?<Link to={`/papers/${encodeURIComponent(r.paper.slug)}`}>{r.paper.title}</Link>:<span>Unavailable paper</span>}<small>{r.status}</small><label htmlFor={`reading-${r.relationId}`}>Reading type</label><select id={`reading-${r.relationId}`} value={r.readingType} disabled={busy} onChange={e=>void change(()=>courseWrite(`${base}/papers/${r.relationId}`,'PATCH',{readingType:e.target.value}))}><option value="required">Required</option><option value="recommended">Recommended</option></select><div className="course-editor-actions"><button type="button" disabled={busy||i===0} aria-label={`Move reading ${r.paper?.title??r.relationId} up`} onClick={()=>move(i,-1)}>Up</button><button type="button" disabled={busy||i===readings.data!.length-1} aria-label={`Move reading ${r.paper?.title??r.relationId} down`} onClick={()=>move(i,1)}>Down</button><button type="button" disabled={busy} aria-label={`Remove reading ${r.paper?.title??r.relationId}`} onClick={()=>void change(()=>courseWrite(`${base}/papers/${r.relationId}`,'DELETE'))}>Remove reading</button></div></li>)}</ol>}
    <form onSubmit={e=>{e.preventDefault();setQ(input.trim());setPage(1)}}><label>Search published papers<input type="search" value={input} onChange={e=>setInput(e.target.value)} /></label><button type="submit">Search papers</button></form>
    <label htmlFor="new-reading-type">Add as</label><select id="new-reading-type" value={readingType} onChange={e=>setReadingType(e.target.value)}><option value="recommended">Recommended</option><option value="required">Required</option></select>
    {papers.loading?<p role="status">Loading papers…</p>:papers.error?<><p role="alert">Paper search unavailable.</p><button type="button" onClick={papers.retry}>Retry papers</button></>:<><ul>{papers.data?.papers.map(p=><li key={p.id}><span>{p.title}</span><button type="button" disabled={busy} aria-label={`Add reading ${p.title}`} onClick={()=>void change(()=>courseWrite(base+'/papers','POST',{paperId:p.id,readingType}))}>Add reading</button></li>)}</ul>{!papers.data?.papers.length&&<p>No matching papers.</p>}<div className="course-editor-actions"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous papers</button><span>Page {papers.data?.pagination.page??page}</span><button type="button" disabled={!papers.data||page>=papers.data.pagination.totalPages} onClick={()=>setPage(p=>p+1)}>Next papers</button></div></>}
  </section>
}
function StaffEditor({base,admin,run,busy}:{base:string;admin:boolean;run:CourseRun;busy:boolean}) {
  const reader=useCallback((signal:AbortSignal)=>courseRequest<{staff:CourseStaffMember[]}>(base+'/staff',{signal}),[base]),staff=useCourseRead(base,reader)
  const [input,setInput]=useState(''),[q,setQ]=useState(''),[page,setPage]=useState(1),[role,setRole]=useState('instructor')
  const candidatesReader=useCallback((signal:AbortSignal)=>admin?courseRequest<{users:{id:number;username:string;email:string}[];total:number}>(`/api/courses/editors?q=${encodeURIComponent(q)}&page=${page}`,{signal}):Promise.resolve(null),[admin,q,page]),candidates=useCourseRead(`${admin}:${q}:${page}`,candidatesReader)
  return <section className="course-editor-panel"><h2>Course staff</h2>{staff.loading?<p role="status">Loading staff…</p>:staff.error?<><p role="alert">Staff unavailable.</p><button type="button" onClick={staff.retry}>Retry staff</button></>:!staff.data?.staff.length?<p>No teachers assigned.</p>:<ul>{staff.data.staff.map(s=><li key={s.id}><span>{s.username} · {s.role}{!s.eligible?' · Inactive or no longer a teacher':''}</span>{admin&&<button type="button" disabled={busy} aria-label={`Remove staff ${s.username}`} onClick={()=>void run(()=>courseWrite(`${base}/staff/${s.id}`,'DELETE'))}>Remove staff</button>}</li>)}</ul>}
    {admin&&<><form onSubmit={e=>{e.preventDefault();setQ(input.trim());setPage(1)}}><label>Search active teachers<input value={input} onChange={e=>setInput(e.target.value)} /></label><button type="submit">Search teachers</button></form><label htmlFor="course-staff-role">Staff role</label><select id="course-staff-role" value={role} onChange={e=>setRole(e.target.value)}><option value="instructor">Instructor</option><option value="assistant">Assistant</option></select>{candidates.loading?<p role="status">Loading teachers…</p>:candidates.error?<><p role="alert">Teacher search unavailable.</p><button type="button" onClick={candidates.retry}>Retry teachers</button></>:<><ul>{candidates.data?.users.map(u=><li key={u.id}><span>{u.username} · {u.email}</span><button disabled={busy} type="button" aria-label={`Assign staff ${u.username}`} onClick={()=>void run(()=>courseWrite(base+'/staff','POST',{userId:u.id,role}))}>Assign staff</button></li>)}</ul><div className="course-editor-actions"><button disabled={page===1} type="button" onClick={()=>setPage(p=>p-1)}>Previous teachers</button><span>Page {page}</span><button disabled={!candidates.data||page*20>=candidates.data.total} type="button" onClick={()=>setPage(p=>p+1)}>Next teachers</button></div></>}</>}
  </section>
}
export default function CourseManagementPage({currentUser}:{currentUser:AuthUser}) {
  const {courseId}=useParams(),id=courseId?Number(courseId):null,{refreshAuth}=useAuth()
  const reader=useCallback((signal:AbortSignal)=>courseRequest<{course?:ManagedCourse;courses?:ManagedCourse[]}>(id===null?'/api/courses/manage':`/api/courses/${id}/manage`,{signal}),[id]),state=useCourseRead(`course-workspace:${id}:${currentUser.id}:${currentUser.role}`,reader)
  const [selected,setSelected]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const run:CourseRun=async action=>{setBusy(true);setError('');setMessage('');try{await action();state.retry();setMessage('Changes saved.');return true}catch(e){setError(e instanceof Error?e.message:'Unable to save.');if(e instanceof CourseManagementError&&[401,403].includes(e.status))await refreshAuth();return false}finally{setBusy(false)}}
  const course=state.data?.course,module=course?.modules.find(m=>m.id===selected)??course?.modules[0],base=`/api/courses/${id}`,moduleBase=`${base}/modules/${module?.id}`
  return <div className="course-management"><header><p>Management · Learning content</p><h1>{course?.title??'Courses'}</h1><Link to="/manage/courses">Assigned courses</Link>{course&&<Link to={coursePath(course.slug)}>View public course</Link>}</header><p role="status" aria-live="polite">{message}</p>{error&&<p role="alert" className="course-editor-error">{error}</p>}<button type="button" onClick={state.retry}>Reload workspace</button>
    {state.loading?<p role="status">Loading course workspace…</p>:state.error?<section className="course-editor-panel"><h2>{state.error==='not-found'?'Course not found':'Workspace unavailable'}</h2><p>Your account may not have access, or the service is unavailable.</p></section>:course?<>
      <ContentEditor key={`${course.id}:${course.updatedAt}`} row={course} base={base} run={run} busy={busy} /><StaffEditor base={base} admin={currentUser.role==='admin'} run={run} busy={busy} /><CourseResourcesEditor base={base+'/resources'} run={run} busy={busy} title="Course resources" />
      <section className="course-editor-panel"><h2>Learning modules</h2><label htmlFor="managed-module">Module to maintain</label><select id="managed-module" value={module?.id??''} onChange={e=>setSelected(Number(e.target.value))}>{course.modules.map(m=><option key={m.id} value={m.id}>Module {m.number} · {m.title}</option>)}</select>{module&&<><p>{module.title}</p><p lang="zh">{module.titleZh}</p><p>{module.durationHours} Hours</p><Link to={modulePath(course.slug,module.slug)}>View public module</Link></>}</section>
      {module&&<div key={module.id}><ContentEditor key={module.updatedAt} row={module} base={moduleBase} module run={run} busy={busy} /><ReadingsEditor base={moduleBase} run={run} busy={busy} /><CourseResourcesEditor base={moduleBase+'/resources'} run={run} busy={busy} title="Module resources" /></div>}
    </>:<div className="course-manage-list">{state.data?.courses?.length?state.data.courses.map(c=><Link key={c.id} to={`/manage/courses/${c.id}`}><h2>{c.title}</h2><p>{c.status} · {c.moduleCount} Modules</p><span>Manage course →</span></Link>):<p>No courses have been assigned to your account.</p>}</div>}
  </div>
}
