"""add papers

Revision ID: 8cadd5a4f419
Revises: 4f2e9a7c1b30
Create Date: 2026-07-22 19:39:01.784885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cadd5a4f419'
down_revision = '4f2e9a7c1b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('publication_type', sa.String(length=50), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('estimated_reading_minutes', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('open_access', sa.Boolean(), nullable=False),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('resource_category', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_papers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_status'))
        batch_op.drop_index(batch_op.f('ix_papers_slug'))
        batch_op.drop_index(batch_op.f('ix_papers_created_by_id'))

    op.drop_table('papers')
    # ### end Alembic commands ###
