"""add paper attachments

Revision ID: b78b852aa4b4
Revises: 8cadd5a4f419
Create Date: 2026-09-05 16:50:51.321888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78b852aa4b4'
down_revision = '8cadd5a4f419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_file_cleanup',
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('storage_key')
    )
    op.create_table('paper_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('external_url', sa.String(length=1500), nullable=True),
    sa.Column('access_level', sa.String(length=30), server_default='public', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(attachment_type = 'external_link' AND external_url IS NOT NULL AND storage_key IS NULL AND sha256 IS NULL AND file_size IS NULL AND mime_type IS NULL AND original_filename IS NULL) OR (attachment_type != 'external_link' AND external_url IS NULL AND storage_key IS NOT NULL AND sha256 IS NOT NULL AND file_size > 0 AND mime_type IS NOT NULL AND original_filename IS NOT NULL)", name='ck_attachment_resource'),
    sa.CheckConstraint("access_level IN ('public', 'authenticated', 'staff')", name='ck_attachment_access'),
    sa.CheckConstraint("attachment_type IN ('pdf', 'cover', 'slides', 'document', 'external_link')", name='ck_attachment_type'),
    sa.CheckConstraint('version >= 1', name='ck_attachment_version'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'attachment_type', 'sha256', name='uq_attachment_sha'),
    sa.UniqueConstraint('storage_key'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('paper_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_attachments_attachment_type'), ['attachment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_attachments_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_attachments_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_attachments_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_index('uq_attachment_primary', ['paper_id', 'attachment_type'], unique=True, sqlite_where=sa.text("attachment_type IN ('pdf', 'cover')"), postgresql_where=sa.text("attachment_type IN ('pdf', 'cover')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_attachments', schema=None) as batch_op:
        batch_op.drop_index('uq_attachment_primary', sqlite_where=sa.text("attachment_type IN ('pdf', 'cover')"), postgresql_where=sa.text("attachment_type IN ('pdf', 'cover')"))
        batch_op.drop_index(batch_op.f('ix_paper_attachments_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_paper_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_paper_attachments_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_attachments_attachment_type'))

    op.drop_table('paper_attachments')
    op.drop_table('attachment_file_cleanup')
    # ### end Alembic commands ###
